name: Deploy Quartz site to GitHub Pages
 
on:
  push:
    branches:
      - master
 
permissions:
  contents: read
  pages: write
  id-token: write
 
concurrency:
  group: "pages"
  cancel-in-progress: false
 
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Build Quartz
        uses: andrea-bonari/quartz@v4
        with:
          site_title: "Sistemi informativi per il settore dell'informazione"
          site_slug: "andrea-bonari.github.io/sistemi-informativi-per-il-settore-dell-informazione"
          site_url: "https://github.com/andrea-bonari/sistemi-informativi-per-il-settore-dell-informazione"
 
  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4